#!/bin/bash
# File: config.sh
# Internal technical configuration for the dynamic blockchain network.
# This script reads high-level settings from the .env file and sets up
# derived variables and constants for other scripts to use.
#
# DO NOT EDIT THIS FILE MANUALLY. Use the .env file for configuration.

# --- Environment Loading ---
# Load environment variables from .env file if it exists.
if [ -f .env ]; then
    set -a
    source .env
    set +a
fi

# --- Dynamic Node Count Configuration ---
# Set the number of nodes based on the active NETWORK_TYPE.
if [ "$NETWORK_TYPE" == "PoA" ]; then
  export NUM_SIGNERS=${POA_SIGNER_COUNT:-3}
  export NUM_NONSIGNERS=${POA_NON_SIGNER_COUNT:-1}
elif [ "$NETWORK_TYPE" == "PoS" ]; then
  export NUM_VALIDATORS=${POS_VALIDATOR_COUNT:-3}
  export NUM_NON_VALIDATORS=${POS_NON_VALIDATOR_COUNT:-1}
fi


# --- Network & Secrets Configuration ---
export NETWORK_ID=${NETWORK_ID:-477748}
export COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME:-"blockchain_sut"}

# Passwords and prefixes are now primarily controlled from .env
export SIGNER_PASS_PREFIX=${SIGNER_PASS_PREFIX:-"pass_signer_"}
export NONSIGNER_PASS_PREFIX=${NONSIGNER_PASS_PREFIX:-"pass_nonsigner_"}

# Secrets for monitoring services and databases.
export ETHSTATS_WS_SECRET=${ETHSTATS_WS_SECRET:-"YourSuperSecretEthstatsStringHere"}
export INFLUXDB_DB=${INFLUXDB_DB:-"geth_metrics"}
export INFLUXDB_USER=${INFLUXDB_USER:-"geth_user"}
export INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD:-"YourStrongInfluxDBPassword"}
export GRAFANA_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-"YourStrongGrafanaAdminPassword"}

# --- Port Mapping Configuration ---
export BASE_GETH_P2P_PORT=${BASE_GETH_P2P_PORT:-30303}
export BASE_GETH_HTTP_PORT=${BASE_GETH_HTTP_PORT:-8545}
export BASE_GETH_WS_PORT=${BASE_GETH_WS_PORT:-8546}
export BASE_MONITORING_HTTP_PORT=${BASE_MONITORING_HTTP_PORT:-8085}
export BASE_GRAFANA_HTTP_PORT=${BASE_GRAFANA_HTTP_PORT:-3000}

# --- Directory and Path Configuration ---
export DATA_DIR="./data"
export CONFIG_DIR="./config"
export SCRIPTS_DIR="./scripts"
export GENESIS_FILE="${CONFIG_DIR}/genesis.json"