# File: docker-compose.yml
version: '3.8'

services:
  # --- Bootnode (Non-Signer 1) ---
  bootnode1:
    image: ethereum/client-go:alltools-v1.13.15
    container_name: bootnode1
    volumes:
      - ./config/genesis.json:/config/genesis.json:ro
      - ./data/bootnode1:/root/.ethereum # Volume untuk chaindata & nodekey
      # Keystore non-signer 1 diperlukan jika Anda ingin menggunakan API 'personal'
      - ./data/nonsigner1/keystore:/root/.ethereum/keystore:ro
      # File password non-signer 1 jika menggunakan API 'personal'
      - ./config/nonsigner1.pass:/root/password.txt:ro
    ports:
      # Port P2P HARUS diekspos agar node lain bisa terhubung
      - "${BOOTNODE1_P2P_PORT:-30303}:${BOOTNODE1_P2P_PORT:-30303}/tcp"
      - "${BOOTNODE1_P2P_PORT:-30303}:${BOOTNODE1_P2P_PORT:-30303}/udp"
      # Port RPC untuk interaksi
      - "${BOOTNODE1_HTTP_PORT:-8545}:8545"
      - "${BOOTNODE1_WS_PORT:-8546}:8546"
    command: >
      geth
      --nodekey /root/.ethereum/geth/nodekey
      --datadir /root/.ethereum
      --keystore /root/.ethereum/keystore
      --networkid "${NETWORK_ID:-2904}"
      --syncmode full
      --gcmode archive
      --port "${BOOTNODE1_P2P_PORT:-30303}"
      --http --http.addr "0.0.0.0" --http.port 8545 --http.api "eth,net,web3,clique,admin,personal" --http.corsdomain "*" --http.vhosts "*"
      --ws --ws.addr "0.0.0.0" --ws.port 8546 --ws.api "eth,net,web3,clique,admin,personal" --ws.origins "*"
      --metrics --metrics.expensive --metrics.influxdb
      --metrics.influxdb.endpoint "http://${INFLUXDB_HOST}:${INFLUXDB_PORT}"
      --metrics.influxdb.database "${INFLUXDB_DB}"
      --metrics.influxdb.username "${INFLUXDB_USER}"
      --metrics.influxdb.password "${INFLUXDB_PASSWORD}"
      --ethstats "bootnode1:${ETHSTATS_WS_SECRET}@ethstats-server:3000"
      --password /root/password.txt
      --allow-insecure-unlock
    networks:
      - geth-network
    restart: unless-stopped

  # --- Signer Node 1 ---
  clef1:
    # image: ethereum/client-go:alltools-v1.13.15
    build:
      context: .
      dockerfile: Dockerfile.clef
    container_name: clef1
    volumes:
      - ./data/signer1/keystore:/root/.ethereum/keystore:ro # Hanya perlu baca keystore
      - ./data/clef1:/root/.clef # Direktori config & data Clef (termasuk masterseed, credentials)
      - ./config/rules.js:/root/rules.js:ro # File aturan
    # Jalankan clef via sh untuk melewati prompt 'ok'
    environment:
      # Sediakan password dan variabel lain yang dibutuhkan skrip expect
      CLEF_MASTER_PASSWORD: ${SIGNER1_PASSWORD}
      NETWORK_ID: ${NETWORK_ID:-2904}
    networks:
      - geth-network
    restart: unless-stopped

  signer1:
    image: ethereum/client-go:alltools-v1.13.15
    container_name: signer1
    depends_on:
      - clef1
      - bootnode1
    volumes:
      - ./config/genesis.json:/config/genesis.json:ro
      - ./data/signer1:/root/.ethereum # Volume untuk chaindata
    ports:
      - "${SIGNER1_HTTP_PORT:-8550}:8545"
      - "${SIGNER1_WS_PORT:-8551}:8546"
    command: >
      geth
      --datadir /root/.ethereum
      --networkid "${NETWORK_ID:-2904}"
      --syncmode full
      --port 30304
      --http --http.addr "0.0.0.0" --http.port 8545 --http.api "eth,net,web3,clique,admin" --http.corsdomain "*" --http.vhosts "*"
      --ws --ws.addr "0.0.0.0" --ws.port 8546 --ws.api "eth,net,web3,clique,admin" --ws.origins "*"
      --metrics --metrics.expensive --metrics.influxdb
      --metrics.influxdb.endpoint "http://${INFLUXDB_HOST}:${INFLUXDB_PORT}"
      --metrics.influxdb.database "${INFLUXDB_DB}"
      --metrics.influxdb.username "${INFLUXDB_USER}"
      --metrics.influxdb.password "${INFLUXDB_PASSWORD}"
      --ethstats "signer1:${ETHSTATS_WS_SECRET}@ethstats-server:3000"
      --bootnodes "${BOOTNODE_ENODE}"
      --signer "http://clef1:8550"
      --mine
      --miner.etherbase "${SIGNER1_ADDRESS}"
    networks:
      - geth-network
    restart: unless-stopped

  # --- Signer Node 2 ---
  clef2:
    build:
      context: .
      dockerfile: Dockerfile.clef
    container_name: clef2
    volumes:
      - ./data/signer2/keystore:/root/.ethereum/keystore:ro
      - ./data/clef2:/root/.clef
      - ./config/rules.js:/root/rules.js:ro
    environment:
      # Sediakan password dan variabel lain yang dibutuhkan skrip expect
      CLEF_MASTER_PASSWORD: ${SIGNER2_PASSWORD}
      NETWORK_ID: ${NETWORK_ID:-2904}
    networks:
      - geth-network
    restart: unless-stopped

  signer2:
    image: ethereum/client-go:alltools-v1.13.15
    container_name: signer2
    depends_on: [clef2, bootnode1]
    volumes:
      - ./config/genesis.json:/config/genesis.json:ro
      - ./data/signer2:/root/.ethereum
    ports:
      - "${SIGNER2_HTTP_PORT:-8552}:8545"
      - "${SIGNER2_WS_PORT:-8553}:8546"
    command: >
      geth --datadir /root/.ethereum --networkid "${NETWORK_ID:-2904}" --syncmode full --port 30305
      --http --http.addr "0.0.0.0" --http.port 8545 --http.api "eth,net,web3,clique,admin" --http.corsdomain "*" --http.vhosts "*"
      --ws --ws.addr "0.0.0.0" --ws.port 8546 --ws.api "eth,net,web3,clique,admin" --ws.origins "*"
      --metrics --metrics.expensive --metrics.influxdb --metrics.influxdb.endpoint "http://${INFLUXDB_HOST}:${INFLUXDB_PORT}" --metrics.influxdb.database "${INFLUXDB_DB}" --metrics.influxdb.username "${INFLUXDB_USER}" --metrics.influxdb.password "${INFLUXDB_PASSWORD}"
      --ethstats "signer2:${ETHSTATS_WS_SECRET}@ethstats-server:3000"
      --bootnodes "${BOOTNODE_ENODE}" --signer "http://clef2:8550" --mine --miner.etherbase "${SIGNER2_ADDRESS}"
    networks:
      - geth-network
    restart: unless-stopped

  # --- Signer Node 3 ---
  clef3:
    build:
      context: .
      dockerfile: Dockerfile.clef
    container_name: clef3
    volumes:
      - ./data/signer3/keystore:/root/.ethereum/keystore:ro
      - ./data/clef3:/root/.clef
      - ./config/rules.js:/root/rules.js:ro
    environment:
      # Sediakan password dan variabel lain yang dibutuhkan skrip expect
      CLEF_MASTER_PASSWORD: ${SIGNER3_PASSWORD}
      NETWORK_ID: ${NETWORK_ID:-2904}
    networks:
      - geth-network
    restart: unless-stopped

  signer3:
    image: ethereum/client-go:alltools-v1.13.15
    container_name: signer3
    depends_on: [clef3, bootnode1]
    volumes:
      - ./config/genesis.json:/config/genesis.json:ro
      - ./data/signer3:/root/.ethereum
    ports:
      - "${SIGNER3_HTTP_PORT:-8554}:8545"
      - "${SIGNER3_WS_PORT:-8555}:8546"
    command: >
      geth --datadir /root/.ethereum --networkid "${NETWORK_ID:-2904}" --syncmode full --port 30306
      --http --http.addr "0.0.0.0" --http.port 8545 --http.api "eth,net,web3,clique,admin" --http.corsdomain "*" --http.vhosts "*"
      --ws --ws.addr "0.0.0.0" --ws.port 8546 --ws.api "eth,net,web3,clique,admin" --ws.origins "*"
      --metrics --metrics.expensive --metrics.influxdb --metrics.influxdb.endpoint "http://${INFLUXDB_HOST}:${INFLUXDB_PORT}" --metrics.influxdb.database "${INFLUXDB_DB}" --metrics.influxdb.username "${INFLUXDB_USER}" --metrics.influxdb.password "${INFLUXDB_PASSWORD}"
      --ethstats "signer3:${ETHSTATS_WS_SECRET}@ethstats-server:3000"
      --bootnodes "${BOOTNODE_ENODE}" --signer "http://clef3:8550" --mine --miner.etherbase "${SIGNER3_ADDRESS}"
    networks:
      - geth-network
    restart: unless-stopped

  # --- Signer Node 4 ---
  clef4:
    build:
      context: .
      dockerfile: Dockerfile.clef
    container_name: clef4
    volumes:
      - ./data/signer4/keystore:/root/.ethereum/keystore:ro
      - ./data/clef4:/root/.clef
      - ./config/rules.js:/root/rules.js:ro
    environment:
      # Sediakan password dan variabel lain yang dibutuhkan skrip expect
      CLEF_MASTER_PASSWORD: ${SIGNER4_PASSWORD}
      NETWORK_ID: ${NETWORK_ID:-2904}
    networks:
      - geth-network
    restart: unless-stopped

  signer4:
    image: ethereum/client-go:alltools-v1.13.15
    container_name: signer4
    depends_on: [clef4, bootnode1]
    volumes:
      - ./config/genesis.json:/config/genesis.json:ro
      - ./data/signer4:/root/.ethereum
    ports:
      - "${SIGNER4_HTTP_PORT:-8556}:8545"
      - "${SIGNER4_WS_PORT:-8557}:8546"
    command: >
      geth --datadir /root/.ethereum --networkid "${NETWORK_ID:-2904}" --syncmode full --port 30307
      --http --http.addr "0.0.0.0" --http.port 8545 --http.api "eth,net,web3,clique,admin" --http.corsdomain "*" --http.vhosts "*"
      --ws --ws.addr "0.0.0.0" --ws.port 8546 --ws.api "eth,net,web3,clique,admin" --ws.origins "*"
      --metrics --metrics.expensive --metrics.influxdb --metrics.influxdb.endpoint "http://${INFLUXDB_HOST}:${INFLUXDB_PORT}" --metrics.influxdb.database "${INFLUXDB_DB}" --metrics.influxdb.username "${INFLUXDB_USER}" --metrics.influxdb.password "${INFLUXDB_PASSWORD}"
      --ethstats "signer4:${ETHSTATS_WS_SECRET}@ethstats-server:3000"
      --bootnodes "${BOOTNODE_ENODE}" --signer "http://clef4:8550" --mine --miner.etherbase "${SIGNER4_ADDRESS}"
    networks:
      - geth-network
    restart: unless-stopped

  # --- Signer Node 5 ---
  clef5:
    build:
      context: .
      dockerfile: Dockerfile.clef
    container_name: clef5
    volumes:
      - ./data/signer5/keystore:/root/.ethereum/keystore:ro
      - ./data/clef5:/root/.clef
      - ./config/rules.js:/root/rules.js:ro
    environment:
      # Sediakan password dan variabel lain yang dibutuhkan skrip expect
      CLEF_MASTER_PASSWORD: ${SIGNER5_PASSWORD}
      NETWORK_ID: ${NETWORK_ID:-2904}
    networks:
      - geth-network
    restart: unless-stopped

  signer5:
    image: ethereum/client-go:alltools-v1.13.15
    container_name: signer5
    depends_on: [clef5, bootnode1]
    volumes:
      - ./config/genesis.json:/config/genesis.json:ro
      - ./data/signer5:/root/.ethereum
    ports:
      - "${SIGNER5_HTTP_PORT:-8558}:8545"
      - "${SIGNER5_WS_PORT:-8559}:8546"
    command: >
      geth --datadir /root/.ethereum --networkid "${NETWORK_ID:-2904}" --syncmode full --port 30308
      --http --http.addr "0.0.0.0" --http.port 8545 --http.api "eth,net,web3,clique,admin" --http.corsdomain "*" --http.vhosts "*"
      --ws --ws.addr "0.0.0.0" --ws.port 8546 --ws.api "eth,net,web3,clique,admin" --ws.origins "*"
      --metrics --metrics.expensive --metrics.influxdb --metrics.influxdb.endpoint "http://${INFLUXDB_HOST}:${INFLUXDB_PORT}" --metrics.influxdb.database "${INFLUXDB_DB}" --metrics.influxdb.username "${INFLUXDB_USER}" --metrics.influxdb.password "${INFLUXDB_PASSWORD}"
      --ethstats "signer5:${ETHSTATS_WS_SECRET}@ethstats-server:3000"
      --bootnodes "${BOOTNODE_ENODE}" --signer "http://clef5:8550" --mine --miner.etherbase "${SIGNER5_ADDRESS}"
    networks:
      - geth-network
    restart: unless-stopped

  # --- Non-Signer Node 2 ---
  nonsigner2:
    image: ethereum/client-go:alltools-v1.13.15
    container_name: nonsigner2
    depends_on: [bootnode1]
    volumes:
      - ./config/genesis.json:/config/genesis.json:ro
      - ./data/nonsigner2:/root/.ethereum # Chaindata
      - ./data/nonsigner2/keystore:/root/.ethereum/keystore:ro # Optional, for personal API
      - ./config/nonsigner2.pass:/root/password.txt:ro # Optional, for personal API
    ports:
      - "${NONSIGNER2_HTTP_PORT:-8562}:8545"
      - "${NONSIGNER2_WS_PORT:-8563}:8546"
    command: >
      geth --datadir /root/.ethereum --keystore /root/.ethereum/keystore --networkid "${NETWORK_ID:-2904}"
      --syncmode full --gcmode archive --port 30309
      --http --http.addr "0.0.0.0" --http.port 8545 --http.api "eth,net,web3,clique,admin,personal" --http.corsdomain "*" --http.vhosts "*"
      --ws --ws.addr "0.0.0.0" --ws.port 8546 --ws.api "eth,net,web3,clique,admin,personal" --ws.origins "*"
      --metrics --metrics.expensive --metrics.influxdb --metrics.influxdb.endpoint "http://${INFLUXDB_HOST}:${INFLUXDB_PORT}" --metrics.influxdb.database "${INFLUXDB_DB}" --metrics.influxdb.username "${INFLUXDB_USER}" --metrics.influxdb.password "${INFLUXDB_PASSWORD}"
      --ethstats "nonsigner2:${ETHSTATS_WS_SECRET}@ethstats-server:3000"
      --password /root/password.txt --allow-insecure-unlock
      --bootnodes "${BOOTNODE_ENODE}"
    networks:
      - geth-network
    restart: unless-stopped

  # --- Non-Signer Node 3 ---
  nonsigner3:
    image: ethereum/client-go:alltools-v1.13.15
    container_name: nonsigner3
    depends_on: [bootnode1]
    volumes:
      - ./config/genesis.json:/config/genesis.json:ro
      - ./data/nonsigner3:/root/.ethereum
      - ./data/nonsigner3/keystore:/root/.ethereum/keystore:ro
      - ./config/nonsigner3.pass:/root/password.txt:ro
    ports:
      - "${NONSIGNER3_HTTP_PORT:-8564}:8545"
      - "${NONSIGNER3_WS_PORT:-8565}:8546"
    command: >
      geth --datadir /root/.ethereum --keystore /root/.ethereum/keystore --networkid "${NETWORK_ID:-2904}"
      --syncmode full --gcmode archive --port 30310
      --http --http.addr "0.0.0.0" --http.port 8545 --http.api "eth,net,web3,clique,admin,personal" --http.corsdomain "*" --http.vhosts "*"
      --ws --ws.addr "0.0.0.0" --ws.port 8546 --ws.api "eth,net,web3,clique,admin,personal" --ws.origins "*"
      --metrics --metrics.expensive --metrics.influxdb --metrics.influxdb.endpoint "http://${INFLUXDB_HOST}:${INFLUXDB_PORT}" --metrics.influxdb.database "${INFLUXDB_DB}" --metrics.influxdb.username "${INFLUXDB_USER}" --metrics.influxdb.password "${INFLUXDB_PASSWORD}"
      --ethstats "nonsigner3:${ETHSTATS_WS_SECRET}@ethstats-server:3000"
      --password /root/password.txt --allow-insecure-unlock
      --bootnodes "${BOOTNODE_ENODE}"
    networks:
      - geth-network
    restart: unless-stopped

  # --- Non-Signer Node 4 ---
  nonsigner4:
    image: ethereum/client-go:alltools-v1.13.15
    container_name: nonsigner4
    depends_on: [bootnode1]
    volumes:
      - ./config/genesis.json:/config/genesis.json:ro
      - ./data/nonsigner4:/root/.ethereum
      - ./data/nonsigner4/keystore:/root/.ethereum/keystore:ro
      - ./config/nonsigner4.pass:/root/password.txt:ro
    ports:
      - "${NONSIGNER4_HTTP_PORT:-8566}:8545"
      - "${NONSIGNER4_WS_PORT:-8567}:8546"
    command: >
      geth --datadir /root/.ethereum --keystore /root/.ethereum/keystore --networkid "${NETWORK_ID:-2904}"
      --syncmode full --gcmode archive --port 30311
      --http --http.addr "0.0.0.0" --http.port 8545 --http.api "eth,net,web3,clique,admin,personal" --http.corsdomain "*" --http.vhosts "*"
      --ws --ws.addr "0.0.0.0" --ws.port 8546 --ws.api "eth,net,web3,clique,admin,personal" --ws.origins "*"
      --metrics --metrics.expensive --metrics.influxdb --metrics.influxdb.endpoint "http://${INFLUXDB_HOST}:${INFLUXDB_PORT}" --metrics.influxdb.database "${INFLUXDB_DB}" --metrics.influxdb.username "${INFLUXDB_USER}" --metrics.influxdb.password "${INFLUXDB_PASSWORD}"
      --ethstats "nonsigner4:${ETHSTATS_WS_SECRET}@ethstats-server:3000"
      --password /root/password.txt --allow-insecure-unlock
      --bootnodes "${BOOTNODE_ENODE}"
    networks:
      - geth-network
    restart: unless-stopped

  # --- Non-Signer Node 5 ---
  nonsigner5:
    image: ethereum/client-go:alltools-v1.13.15
    container_name: nonsigner5
    depends_on: [bootnode1]
    volumes:
      - ./config/genesis.json:/config/genesis.json:ro
      - ./data/nonsigner5:/root/.ethereum
      - ./data/nonsigner5/keystore:/root/.ethereum/keystore:ro
      - ./config/nonsigner5.pass:/root/password.txt:ro
    ports:
      - "${NONSIGNER5_HTTP_PORT:-8568}:8545"
      - "${NONSIGNER5_WS_PORT:-8569}:8546"
    command: >
      geth --datadir /root/.ethereum --keystore /root/.ethereum/keystore --networkid "${NETWORK_ID:-2904}"
      --syncmode full --gcmode archive --port 30312
      --http --http.addr "0.0.0.0" --http.port 8545 --http.api "eth,net,web3,clique,admin,personal" --http.corsdomain "*" --http.vhosts "*"
      --ws --ws.addr "0.0.0.0" --ws.port 8546 --ws.api "eth,net,web3,clique,admin,personal" --ws.origins "*"
      --metrics --metrics.expensive --metrics.influxdb --metrics.influxdb.endpoint "http://${INFLUXDB_HOST}:${INFLUXDB_PORT}" --metrics.influxdb.database "${INFLUXDB_DB}" --metrics.influxdb.username "${INFLUXDB_USER}" --metrics.influxdb.password "${INFLUXDB_PASSWORD}"
      --ethstats "nonsigner5:${ETHSTATS_WS_SECRET}@ethstats-server:3000"
      --password /root/password.txt --allow-insecure-unlock
      --bootnodes "${BOOTNODE_ENODE}"
    networks:
      - geth-network
    restart: unless-stopped

  # --- Monitoring Stack ---
  ethstats-server:
    build:
      context: https://github.com/goerli/ethstats-server.git # Build dari Goerli fork
    container_name: ethstats-server
    environment:
      WS_SECRET: "${ETHSTATS_WS_SECRET}"
      # PORT, RPC_HOST, RPC_PORT diatur oleh entrypoint repo
    ports:
      - "${ETHSTATS_PORT:-8080}:3000" # Ekspos port internal 3000 ke host
    networks:
      - geth-network
    restart: unless-stopped

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      INFLUXDB_DB: "${INFLUXDB_DB}"
      INFLUXDB_ADMIN_USER: "${INFLUXDB_USER}"
      INFLUXDB_ADMIN_PASSWORD: "${INFLUXDB_PASSWORD}"
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_USER: "${INFLUXDB_USER}"
      INFLUXDB_USER_PASSWORD: "${INFLUXDB_PASSWORD}"
    networks:
      - geth-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    depends_on:
      - influxdb
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: "${GRAFANA_ADMIN_PASSWORD}" # Ambil dari .env
    networks:
      - geth-network
    restart: unless-stopped

# --- Network Definition ---
networks:
  geth-network:
    driver: bridge
    name: ${COMPOSE_PROJECT_NAME}_default_net # Beri nama jaringan agar lebih mudah diidentifikasi

volumes:
  grafana_data: {}
  influxdb_data: {}